# Generated by Django 4.2.4 on 2023-08-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bitcoin_address',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='card_number',
            field=models.CharField(default=0, max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ethereum_address',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default='Ivanovich', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='passport_number',
            field=models.CharField(default='MB0', max_length=20),
        ),
    ]
